name: Pac-Man Katkı Grafiğini Üret

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - profile-readme-game-mode
    paths:
      - README.md
      - .github/workflows/pacman.yml

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Pac-Man katkı grafiğini üret
        uses